### ISSUE TITLE
Delay before screenshot

### ISSUE THREAD

**Issue by bookin** [juliangruber/capture-chrome#2]
Hello,

Do you know how to add a delay before taking screenshot? 
For example, I need make screenshot after video loaded on the youtube, to have a preview on the screenshot.

Thanks.

**Comment by juliangruber** [comment]
not sure, maybe there's an extra option that we can pass to the `chrome` cli? https://github.com/juliangruber/capture-chrome/blob/master/index.js#L17

**Comment by bookin** [comment]
I found option - `--virtual-time-budget`, but for some reason, it doesn't work for some sites,
I decide to use GoogleChrome/puppeteer so it decides my problem,
Thanks for the help!

**Comment by juliangruber** [comment]
Sure!
