### ISSUE TITLE
Can't install because of puppeteer issue

### ISSUE THREAD

**Issue by kolyasya** [juliangruber/capture-chrome#6]
Hello, thank you for a package.
There is a problem while installing:

![image](https://user-images.githubusercontent.com/3371143/44990809-eb29a700-af9a-11e8-9227-2ebeb92b0bfa.png)

**Comment by juliangruber** [comment]
You most likely need to update your node version, what are you currently using?

**Comment by kolyasya** [comment]
@juliangruber I try to use you package with my Meteor 1.5 app, which seems to have a Node 6 version.

Which lowest version are you suggesting to use?

**Comment by kolyasya** [comment]
Updating to Meteor 1.6 helped, thank you ;-)

**Comment by juliangruber** [comment]
Great!
